INSERT INTO BRANCH (BRANCH_ID, BRANCH_NAME, TIME_FROM, TIME_TO)
VALUES (1, 'Pune', '01:00:00', '02:00:00');

INSERT INTO BRANCH (BRANCH_ID, BRANCH_NAME, TIME_FROM, TIME_TO)
VALUES (2, 'Mumbai', '01:00:00', '03:00:00');

INSERT INTO BRANCH (BRANCH_ID, BRANCH_NAME, TIME_FROM, TIME_TO)
VALUES (3, 'Chennai', '01:00:00', '04:00:00');

INSERT INTO BRANCH (BRANCH_ID, BRANCH_NAME, TIME_FROM, TIME_TO)
VALUES (4, 'Delhi', '01:00:00', '05:00:00');



INSERT INTO VACCINE(VACCINE_ID, VACCINE_NAME)
VALUES (1, 'Covid');

INSERT INTO VACCINE(VACCINE_ID, VACCINE_NAME)
VALUES (2, 'Ebola');

INSERT INTO VACCINE(VACCINE_ID, VACCINE_NAME)
VALUES (3, 'Chicken Pox');

INSERT INTO VACCINE(VACCINE_ID, VACCINE_NAME)
VALUES (4, 'Polio');

INSERT INTO BRANCH_VACCINE(BRANCH_VACCINE_ID , VACCINE_COUNT ,BRANCH_ID ,VACCINE_ID )
VALUES (1,1,1,1);

INSERT INTO BRANCH_VACCINE(BRANCH_VACCINE_ID , VACCINE_COUNT ,BRANCH_ID ,VACCINE_ID )
VALUES (1,2,2,3);

INSERT INTO BRANCH_VACCINE(BRANCH_VACCINE_ID , VACCINE_COUNT ,BRANCH_ID ,VACCINE_ID )
VALUES (3,2,3,3);

